apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyterlab-deployment
  labels:
    app: jupyter
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jupyter
  template:
    metadata:
      labels:
        app: jupyter
    spec:
      containers:
      - name: jupyter
        image: sebjul06/deeplearning-notebook:latest
        ports:
        - containerPort: 8888
        command:
            - /bin/bash
            - -c
            - |
              start.sh jupyter lab --LabApp.token='password' --LabApp.ip='0.0.0.0' --LabApp.allow_root=True